networks:
  my_network:

services:
  app:
    build:
      context: .
      dockerfile: wiki_parser_app/Dockerfile
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    command: bash -c "alembic -c /alembic.ini upgrade head;uvicorn wiki_parser_app.main:app --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - my_network


  db:
    image: postgres:16-alpine
    restart: on-failure
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    expose:
      - "5432"
    volumes:
      - ./pg_data/:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "-c", "pg_isready -U $POSTGRES_USER" ]
      interval: 10s
      retries: 5
      timeout: 5s
    networks:
      - my_network


volumes:
  pg_data:
